### ISSUE TITLE
The plugin doesn't work with Notepad++ v 7.6.3

### ISSUE THREAD

**Issue by ethren** [nea/MarkdownViewerPlusPlus#100]
Recently I uninstalled Notepad++ 32bit that has `MarkdownViewer++` and I installed Notepad++ x64 version, but the plugin MarkdownViewer does not work. I tried to install it from **Plugins admin** and manually by downloading it and adding `MarkdownViewerPlusPlus.dll` to `plugins` folder. In both cases, the plugin doesn't appear in the toolbar.

**Comment by pryrt** [comment]
@ethren ,

Notepad++ v7.6.3 has a different plugin structure than v7.5.9 and earlier: each plugin gets its own subdirectory of the `plugins` folder.  Instead of putting it in `directory\plugins\MarkdownViewerPlusPlus.dll`, put it in `directory\plugins\MarkdownViewerPlusPlus\MarkdownViewerPlusPlus.dll`

**Comment by ethren** [comment]
@pryrt 
Thank you very much, that solved it. I didn't know about that
