### ISSUE TITLE
File extensions not working

### ISSUE THREAD

**Issue by xomx** [nea/MarkdownViewerPlusPlus#14]
Does not work as expected:
- setting Options->General->File extensions -> log -> Save
- opening a file.log with plugin active == message:
Your configuration settings do not include the currently selected file extension.
The rendered file extensions are 'log'.
The current file is 'file.log'. False
- clicking View-Refresh works

**Comment by dail8859** [comment]
Looks like we submitted the same issue at the exact same time ;) See #13 which has been closed now.

**Comment by nea** [comment]
Damn it. Too distracted ^^° Will build a new version soon.

Thanks

**Comment by nea** [comment]
Big sorry about the delay.

A new version is up, 0.5.1 (https://github.com/nea/MarkdownViewerPlusPlus/releases).

This time I tested all option I could think of. Don't know what happened last time. Left in debug outputs and didn't correctly validate the check. Sorry about that.

Hope this is good now, otherwise let me know :)


Cheers
