### ISSUE TITLE
Project targets a nonexistent HtmlRenderer package version

### ISSUE THREAD

**Issue by vaindil** [nea/MarkdownViewerPlusPlus#64]
This project is targeting version `1.5.1-beta2` of the `HtmlRenderer` packages, but that version [does not exist](https://www.nuget.org/packages/HtmlRenderer.Core). The most recent version is `1.5.1-beta1`. I'm not sure how to build this with a nonexistent package.

**Comment by nea** [comment]
Hi @vaindil 

Yes, that is known because I had to update another library and by that HTMLRenderer. As they are currently not 100% active my PR is still open at https://github.com/ArthurHub/HTML-Renderer/pull/119. You can check out that PR and add it to a local nuget (what I did).

I hope it will be merged soon.


Sorry for the inconvenience.
