### ISSUE TITLE
Unresolved reference not allowed: PdfSharp

### ISSUE THREAD

**Issue by DimitrijeK** [nea/MarkdownViewerPlusPlus#84]
## Issue description
Hey everybody, hope somebody can help me! Recently I downloaded this repository and opened it in 
Microsoft VS 2017 and after trying to build the solution I got this error:

           -Unresolved reference not allowed: PdfSharp

Not really sure why, I am pretty sure I have all the packages I need installed. I know its problem in ILMerge when trying to merge all assemblies into one dll file, but don't really know how to fix it.

### Screenshot
![capture](https://user-images.githubusercontent.com/29495555/41593579-d5e5d69a-73c0-11e8-87ae-4e1607b1396d.PNG)
![capture2](https://user-images.githubusercontent.com/29495555/41593580-d605abfa-73c0-11e8-9022-de3f146e2601.PNG)

### Environment
* Windows 7 (64-bit OS)

**Comment by nea** [comment]
Hi @DimitrijeK 

Please refer to #70. 

The reason you cannot build it is because I have a custom PDFSharp Version in my personal, local NuGet that wasn't available when I was building it, because I updated some dependencies I required on all ends in HTMLRenderer etc. As soon as PDFSharp is updated, too, I will switch back.

You would have to checkout HTMLRenderer yourself and update PDFSharp accordingly in it to have all references as it is not maintained anymore.


Sorry

**Comment by DimitrijeK** [comment]
Hi @nea , thank you this helped a lot. I was able to build succesfully, but now I am having issues with ANSI not being compatible with unicode notepad++. But thats a different issue now. Thank you!

**Comment by bhu1st** [comment]
Getting the same issue... 

`Unresolved reference not allowed: PdfSharp`

@DimitrijeK How did you resolve it?
