### ISSUE TITLE
[bug] new line before list element text

### ISSUE THREAD

**Issue by mrdragonslayer** [nea/MarkdownViewerPlusPlus#86]
## Issue description
Cause: there is an empty line between 2 elements of a list in the markdown
Consequence: in the rendered text all the list item-texts are on a new line with respect to the item-symbol 

### Markdown to reproduce

```
* text

* text
```
### Screenshot
![image](https://user-images.githubusercontent.com/40538901/42866891-387bff64-8a6e-11e8-909e-cf0cb084db75.png)

### Environment
* Notepad++ 7.5.6 (x32)
* MarkdownViewer++ 0.8.2.0
* Windows 7 (x86)

**Comment by nea** [comment]
Hi @mrdragonslayer 

Please refer to #47 and #39. This is a loose list because of the space in-between, which is not supported at the moment without changing the renderer completely, which is not part of the current project.

I am looking into other options but this "works as implemented" for now.


Sorry
